# Common Application properties
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html

# -------------------------------------------------------------------------------------------------------------
# DATA PROPERTIES
# -------------------------------------------------------------------------------------------------------------

spring:

  # H2DB - http://localhost:${server.port}/h2-console/login.do
  h2:
    # H2 Web Console (H2ConsoleProperties)
    console:
      # Whether to enable the console.
      enabled: true
      # Path at which the console is available.
      path: /h2-console/
      # Whether to enable trace output.
      settings:
        trace: false
        # Whether to enable remote access.
        web-allow-others: false
  
  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    # JDBC URL of the database.
    url: jdbc:h2:mem:jhac;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    # Fully qualified name of the JDBC driver. Auto-detected based on the URL by default.
    driverClassName: org.h2.Driver
    # Username of the database to execute DML scripts (if different).
    username: sa
    # Password of the database to execute DML scripts (if different).
    password:
  
  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    # Name of the target database to operate on, auto-detected by default. Can be alternatively set using the "Database" enum.
    database-platform: org.hibernate.dialect.H2Dialect
    # Print the queries
    show-sql: true
    # Pretty print the SQL
    properties:
      hibernate:
        format_sql: true

  hibernate:
    # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property.
    # Defaults to "create-drop" when using an embedded database and no schema manager was detected.
    # Otherwise, defaults to "none".
    ddl-auto: update

# -------------------------------------------------------------------------------------------------------------
# DATA MIGRATION PROPERTIES
# -------------------------------------------------------------------------------------------------------------

  flyway:
    # Whether to enable flyway.
    enabled: false
    # Locations of migrations scripts. Can contain the special "{vendor}" placeholder to use vendor-specific locations.
    locations: classpath:/data/h2db/migrations